export interface Location { latitude: number; longitude: number; display_name?: string | null; country?: string | null; region?: string | null; }
export interface ProvenanceRecord { source_name: string; source_type: string; dataset_or_reference?: string | null; url?: string | null; citation?: string | null; retrieved_at?: string | null; observation_time?: string | null; license?: string | null; spatial_resolution?: string | null; temporal_resolution?: string | null; processing_steps: string[]; quality_notes: string[]; }
export interface ClimateObservation { source: string; source_dataset: string; variable: string; value?: number | null; unit?: string | null; timestamp: string; latitude: number; longitude: number; spatial_resolution?: string | null; temporal_resolution?: string | null; quality?: string | null; provenance: ProvenanceRecord; }
export type SoilMoistureLayer = "surface" | "root_zone";
export interface SoilMoistureObservation { source: string; dataset: string; layer: SoilMoistureLayer; value?: number | null; unit?: string | null; timestamp: string; latitude: number; longitude: number; spatial_resolution?: string | null; quality?: string | null; provenance: ProvenanceRecord; }
export interface SoilProfile { source_type?: string | null; measurement_date?: string | null; depth?: string | null; texture?: string | null; pH?: number | null; salinity?: number | null; organic_matter?: number | null; nitrogen?: number | null; phosphorus?: number | null; potassium?: number | null; drainage?: string | null; water_holding_capacity?: number | null; provenance: ProvenanceRecord[]; }
export interface CropProfile { id: string; common_name: string; scientific_name?: string | null; family?: string | null; climate_requirements: Record<string, unknown>; soil_requirements: Record<string, unknown>; water_requirements: Record<string, unknown>; rotation_traits: Record<string, unknown>; sources: ProvenanceRecord[]; review_status?: string | null; }
export interface FarmerPriorities { water_conservation?: number | null; soil_health?: number | null; resilience?: number | null; productivity?: number | null; }
export interface RotationScenario { id: string; periods: string[]; crop_ids: string[]; generation_method?: string | null; source_rules: string[]; }
export interface ScientificScenarioProfile { climate_assessment?: Record<string, unknown> | null; soil_assessment?: Record<string, unknown> | null; water_context?: Record<string, unknown> | null; rotation_assessment?: Record<string, unknown> | null; limiting_factors: string[]; benefits: string[]; risks: string[]; unknowns: string[]; uncertainties: string[]; evidence: ProvenanceRecord[]; }
